[package]
name = "cgi"
version = "0.1.0"
authors = ["prataprc <prataprc@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[example]]
name = "files"

[dependencies]
ttf-parser = "0.12.0"
bmp = "0.5.0"

[dev-dependencies]
rustybuzz = "0.3.0"
prettytable-rs = "0.8.0"
structopt = "*"
