[package]
name = "cgi"
version = "0.1.0"
authors = ["prataprc <prataprc@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "vkinfo"
path = "src/bin/vkinfo/main.rs"

[[bin]]
name = "fonts"
path = "src/bin/fonts/main.rs"

[[example]]
name = "files"

[[example]]
name = "vk"

[dependencies]
structopt = "*"
prettytable-rs = "0.8.0"
colored = "2.0.0"
uuid = "0.8"

ttf-parser = "0.12.0"
bmp = "0.5.0"

specs = { version = "0.16.1", features = ["specs-derive"] }
vulkano = { version = "0.22", path = "/home/prataprc/devrs/vulkano/vulkano/" }
vk-sys = { version = "0.6.0", path = "/home/prataprc/devrs/vulkano/vk-sys/" }
vulkano-win = { version = "0.22", path = "/home/prataprc/devrs/vulkano/vulkano-win/" }
vulkano-shaders = { version = "0.22", path = "/home/prataprc/devrs/vulkano/vulkano-shaders/" }
winit = "0.24.0"

[dev-dependencies]
rustybuzz = "0.3.0"
