[package]
name = "cgi"
version = "0.1.0"
authors = ["prataprc <prataprc@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[example]]
name = "files"

[[example]]
name = "vk"

[dependencies]
ttf-parser = "0.12.0"
bmp = "0.5.0"

specs = { version = "0.16.1", features = ["specs-derive"] }
vulkano = { version = "0.21", path = "/home/prataprc/graphics/vulkano/vulkano/" }
glfw = "0.41.0"
uuid = "0.8"

[dev-dependencies]
rustybuzz = "0.3.0"
prettytable-rs = "0.8.0"
structopt = "*"
