[package]
name = "cgi"
version = "0.1.0"
authors = ["prataprc <prataprc@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "ttf"
path = "src/bin/ttf/main.rs"

[dependencies]
ttf-parser = { version = "0.12.0", optional = true }
prettytable-rs = { version = "0.8.0", optional = true }
structopt = { version = "*", default-features = false }

[features]
ttf = ["ttf-parser", "prettytable-rs"]
