web = false

[adapter]
power_preference = "low_power"
force_fallback_adapter = false

[winit]
title = "gpgpu"
visible = true
transparent = false
alway_on_top = false
maximized = false
minimised = false
resizable = true
cursor_position = [0, 0]
cursor_visible = true
decorations = true
inner_size = [800, 600]
max_inner_size = [800, 600]
min_inner_size = [800, 600]
position = [0, 0]
# TODO: ime_position
# TODO: cursor_icon
# TODO: fullscreen
# TODO: window_icon: Option<ffi::OsString>,
